# ==== 配置输出路径 ====
classes_file = 'classes.txt'

# ==== 66 类交通标志名称 ====
classes = [
    "U-turn",
    "Keep right",
    "Keep left",
    "Pass either side",
    "Compulsory motor-cycles track",
    "Stop",
    "No Left Turn",
    "No right turn",
    "No U-turn",
    "No entry",
    "Weight limit sign 5T",
    "Weight limit sign 30T",
    "Height limit sign 2.-m",
    "Height limit sign 3.-m",
    "Height limit sign 4.-m",
    "Height limit sign 5.-m",
    "Height limit sign 6.-m",
    "Speed Limit 20",
    "Speed Limit 30",
    "Speed Limit 40",
    "Speed Limit 50",
    "Speed Limit 60",
    "Speed Limit 70",
    "Speed Limit 80",
    "Speed Limit 90",
    "Speed Limit 110",
    "No Entry for Vehicles Exceeding 5T",
    "Heavy vehicles no driving on right lane",
    "No Parking",
    "No Stopping",
    "Give way",
    "Wide limit 3.5m",
    "No overtaking",
    "Road Work",
    "Camera operation zone",
    "Crosswind area",
    "Caution! Hump",
    "Hump ahead",
    "Towing zone",
    "Left bend",
    "Slippery road",
    "Pedestrian crossing opt1",
    "Pedestrian crossing opt2",
    "School children crossing opt1",
    "School children crossing opt2",
    "Caution",
    "Narrow roads on the left",
    "Traffic lights ahead",
    "Obstacles ahead",
    "Staggered junctions",
    "Crossroads T-junction",
    "Crossroads to the right",
    "Crossroads to the left",
    "Exit to the left",
    "Crossroads",
    "Minor road on right",
    "Minor road on left",
    "Minor road on left opt2",
    "Cattle crossing",
    "Roundabout ahead",
    "Narrow bridge",
    "Split way",
    "Two way road",
    "Divided road ending",
    "Curve on the left",
    "Crossroads Y-junction"
]

# ==== 写入文件 ====
with open(classes_file, 'w') as f:
    for name in classes:
        f.write(name + '\n')

print(f"classes.txt 已生成，包含 66 类名称，路径：{classes_file}")
